### ISSUE TITLE
Frontend unmatched paths coming back 200

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-spar#118]
Frontend unhandled paths are returning 200 codes, which is unexpected behaviour.  This, for example, passed in the pipeline, despite the path not existing.

https://nr-spar-116-frontend.apps.silver.devops.gov.bc.ca/actuator/health

**Comment by mgaseta** [comment]
Did some research and this is not something easy to change on the FE only.

We already redirect nonexistent paths back to the dashboard or to an 404 error page, and because this redirection leads to an existent page, even if the URL is wrong, the request will return a status code 200.

To make the status change we would need some changes on the server side, like this: https://stackoverflow.com/questions/54727226/react-returns-a-200-for-a-page-not-found

Also, the current version we are using for react-router doesn't let us "simulate" the response status.

Since this is a low-priority issue, I'll return this to the backlog, I suggest another peer take a look at this and if turns out it's way too complicate to deal with, we just accept it and live with the current behavior.

**Comment by DerekRoberts** [comment]
@mgaseta How about this?  https://github.com/bcgov/nr-spar/pull/749

**Comment by mgaseta** [comment]
Hmmm, I'm still getting the 200 return, maybe we are talking about different returns?
I'm looking at the request for the page in the browser console, this is current behavior:

![Screenshot from 2024-01-09 16-20-13](https://github.com/bcgov/nr-spar/assets/105936322/cfc51bee-ed70-43a1-aebc-7e55d7070af3)
