### ISSUE TITLE
Corrections for /api/orchards/parent-tree-genetic-quality/{orchardId}/{spuId\

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#184]
Description:

Further work/corrections are needed the for /api/orchards/parent-tree-genetic-quality/{orchardId}/{spuId} endpoint. Currently it is pulling some nonsense data when invalid Seed Planning Unit codes are entered. For example, when an invalid SPU code is entered, random parent tree data is pulled that doesn't actually exist.
 

![Image](https://user-images.githubusercontent.com/64149835/242749911-53885bef-7a08-4904-9d4a-86463444dd01.png)

Acceptance Criteria:

When an SPU code that doesn't exist is entered, then an error is received
When there is an invalid Orchard ID and SPU combination an error is received. Going forward orchard ID and SPU will have a 1:1 relationship.

**Comment by RMCampos** [comment]
Indeed. Today we have no validation at all for SpuId. This is an `oracle-api` endpoint. Since the source of truth (tables and rules) are on the `backend api`, to get this fixed we would need to have a call/request from `oracle-api` to `backend`. It will work, but we can make it better.

Combining @craigyu 's idea, about having just one request with `OrchardId` and then receiving all Parent Tree and Genetic Quality data with this bug, I suggest we update `backend api`, to respond with all data where today there is a call to get the `SpuId`, and the `backend api` calls `oracle-api` to fetch Parent Tree and Genetic Quality data, leaving all complexity and rules in one place, in this case, the `backend api`.

Maybe it got a bit complex. But it would fix two major issues.

Here's a small diagram to help understanding
![orchardId-and-spuId2](https://github.com/bcgov/nr-spar/assets/2219519/60902b57-4eec-49d8-ae7c-a5e55686000b)

If everyone agree, I can update this task to cover all changes. @SLDonnelly and @craigyu
