### ISSUE TITLE
Bug in Orchard screen

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#204]
Description:

There is a bud in the orchard screen that was noticed during testing. When a second orchard is entered, the appropriate orhcard name, number and species does not get populated. 

![Image](https://github.com/bcgov/nr-spar/assets/64149835/09a7f034-043e-4288-b8ae-dcaf1cbbd243)

Acceptance Crtiteria:

For the second orchard, the correct species, orchard name and stage should occur. For example, if the orchard number 321 is entered, the species code Fdi, orchard name "Grandview" and orchard stage "PRD" should be populated.

**Comment by craigyu** [comment]
![Image](https://github.com/bcgov/nr-spar/assets/25162561/ee9fd6d8-b4f2-46f9-b41f-321a8efba982)

Nice catch, there are two bugs happening in your screenshot:

1. the orchard name is not being displayed full due to screen size
2. the second orchard name is not updated, was 993 entered in the second orchard ID then later changed to 321?
