### ISSUE TITLE
Enable Oracle API to send logs to OpenSearch

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#386]
Following same changes to `Backend API`, update the `Oracle API` service allowing it to send logs to OpenSearch.

- Backend API PR: https://github.com/bcgov/nr-spar/pull/202
- Backend API Issue: https://github.com/bcgov/nr-spar/issues/203

Updates on October, 4th:
Pending items for this task
- [x] Changes pushed into Funbucks. Here: https://github.com/bcgov-nr/nr-funbucks/pull/478
- [x] Test lambda parsing locally with apm and event stream processing

**Comment by mgaseta** [comment]
Stealing this one for me :ninja: 🦹

**Comment by mgaseta** [comment]
Moving to blocked for 2 reasons:
- We need to talk with OneTeam about how to make one instance of the fluentbit deal with the logs of both the `Backend API` and the `Oracle API`.
- I can't connect to BC Gov's VPN due an certificate issue, I'm already talking with Encora's IT team to solve this.

For now, all the changes are pushed to the working branch, they can be checked here: https://github.com/bcgov/nr-spar/commit/7e5d2b40f40f57a04d36307431f6a971efc07c42

**Comment by SLDonnelly** [comment]
@mbystedt @andrwils would either of you be able to help Matheus with the issue described above? Matheus can provide any additional info that you need

**Comment by mbystedt** [comment]
> * We need to talk with OneTeam about how to make one instance of the fluentbit deal with the logs of both the `Backend API` and the `Oracle API`.

I think we're missing some information about the ask here. Feel free to setup a meeting. One instance of Fluentbit can easily handle quite a number of different sources of logs. There's no difference between having a single input source or 10. The only thing that becomes complicated is tags. We came up with a couple strategies for keeping tags straight in Funbucks for the on-premise that we can share.

**Comment by mgaseta** [comment]
Sorry, that was already solved, I forgot to update the ticket... The situation right now is that we can't see the generated logs on opensearch, we just need to get some directions on how to make it work! You can check the changes we made on [this PR](https://github.com/bcgov/nr-spar/pull/436), which is also linked to this issue. Thanks!

**Comment by mbystedt** [comment]
@mgaseta Well, now I know who's responsible for the 8000+ errors triggering our alerts. This change should be rolled back until the Fluentbit configuration is fixed.

I can take a look at the output from FluentBit. But, it'll be much quicker if you just use the public docker image (artifacts.developer.gov.bc.ca/cc20-gen-docker-local/nr-funbucks:latest) that can be used to test your output. Unless it's exceedingly obvious, that's what I will be doing, anyway. Docs are here: https://bcdevops.github.io/nr-apm-stack/#/testing

I'll update this with the docker command. `podman run -d -p 3000:3000 artifacts.developer.gov.bc.ca/cc20-gen-docker-local/nr-funbucks:latest`

Since it's not a Funbucks template, I have no way to generate a local FluentBit setup. You're on your own with the configuration unless you can provide that local equivalent. Your pipeline to getting new logs to production should have a way to generate a local FluentBit setup. Otherwise, you'll be wasting a lot of time copying and pasting and modifying things manually.

**Comment by RMCampos** [comment]
Hi @mbystedt so sorry about all of those errors. We forgot to delete the PR deployment, since that was only a preview. Now is gone.

There should be a Funbucks template, though. I'll push a commit and open a PR on Funbucks repo. Very likely we'll need some help to do those changes, but I think we can use the PR comments section :) 

Once we have Funbucks in place, we can work with `nr-apm-stack-lambda`. 

Thanks for the help, as always. 

cc: @mgaseta @SLDonnelly

**Comment by mbystedt** [comment]
@RMCampos Excellent. Once there's that template PR in Funbucks, if you give us a sample then we'll be able to have a better idea what is the problem. The errors are about it not having an index. So, it's likely a fingerprint issue.

Let us know if that lambda container works for you. We moved all the integration docs to [https://bcdevops.github.io/nr-apm-stack](https://bcdevops.github.io/nr-apm-stack/#/testing). Welcome any thoughts you have. Feel free to do a PR if you want to. The files in the docs folder of the [https://github.com/BCDevOps/nr-apm-stack/tree/main/docs](apm-stack repo).
