### ISSUE TITLE
Design system update - Change the fields' label

### ISSUE THREAD

**Issue by thiagosanchezenc** [bcgov/nr-spar#423]
Design system update - Change the fields' label (text/area/number/search/checkbox/radio button, etc.) to use "primary-text" instead of "secondary-text"

Check with @mmarsoleta for more info.

**Comment by mgaseta** [comment]
The label color is assigned to be changed on the the design system, is not SPAR specific, I raised an [issue](https://github.com/bcgov/nr-fsa-theme/issues/78) on their repository.

Moving this to block, for now

**Comment by mmarsoleta** [comment]
[like]  Michelly Beatriz Marsoleta reacted to your message:
________________________________

**Comment by mgaseta** [comment]
Also fixed 2 other bugs related to the update to use the `nr-fsa-theme`: one related to the text-style for checkboxes labels and other related to the accordion component size on the form review.

Since they are small changes we agreed to fix them in this issue.

The fixes can be checked [here](https://github.com/bcgov/nr-spar/commit/38fdad3c3315c8e1748cc774db810338f04bb4a4) and [here](https://github.com/bcgov/nr-spar/commit/1bed77e72e3dfe1b98073c2b15ddfd3856c06e50)

**Comment by mgaseta** [comment]
Updated the issue for the new board of the Design System Team, link [here](https://github.com/bcgov/nr-theme/issues/97).
