### ISSUE TITLE
Test cypress on github action

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#493]
This ticket aims to have cypress e2e test running on GHA as part of the CI/CD.

**Comment by DerekRoberts** [comment]
@craigyu We have some smelly, old code for this that was commented out because Cypress was failing, blocking workflows.  If fixed this should probably be moved to `.github/workflows/ci.yml`.

https://github.com/bcgov/nr-spar/blob/main/.github/workflows/pr-open.yml#L209

I don't see much value in maintaining `.github/workflows/cypress-nightly.yml`.
