### ISSUE TITLE
Responsiveness standards documentation

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#745]
**As a** *PO/DEV/Interested Party* **I want** *documentation **on ** *responsiveness standards for clarity and reference*

**Acceptance Criteria**
- [ ] Documented on SPAR Github Wiki
- [ ] Comprehensive and answers the who, what, when, where and why of responsiveness standards

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Documentation and/or scientific documentation exists and can be found

**Comment by kevinginley** [comment]
Here's what I have so far:

[Why we use Responsive Design.docx](https://github.com/bcgov/nr-spar/files/14070738/Why.we.use.Responsive.Design.docx)

@SLDonnelly @mmarsoleta Anything you'd recommend adding, removing, or otherwise changing? I've turned "Tracked Changes" on in the .doc. Thank you!

**Comment by mmarsoleta** [comment]
> Here's what I have so far:
> 
> [Why we use responsive design.doc](https://bcgov.sharepoint.com/:w:/r/teams/07176/Shared%20Documents/General/UX%20Team/SPAR%20%26%20CONSEP%20(1)/Documentation/Why%20we%20use%20responsive%20design/Why%20we%20use%20Responsive%20Design.docx?d=w294a9cf0fa5441419d9fbf92478029e2&csf=1&web=1&e=vlndRF)
> 
> [@SLDonnelly](https://github.com/SLDonnelly) [@mmarsoleta](https://github.com/mmarsoleta) Anything you'd recommend adding, removing, or otherwise changing? I've turned "Tracked Changes" on in the .doc. Thank you!

The doc is looking good, thank you Kevin, nice work. 🥳

I was happy to see the accessibility section because for me it was me main reason why we were designing for small screen. There is one WCAG success criteria called "Reflow" - It is a good justification on why having the screens developed using 320px is a good thing as well. (to support 400% zoom without breaking the layout and avoid having vertical and horizontal scrolls at the same time on the website/mobile). It could be a good source to add to the doc as well ([https://www.w3.org/WAI/WCAG21/Understanding/reflow.html]

**Comment by kevinginley** [comment]
Thanks Michelly! I've incorporated that into the .doc

**Comment by kevinginley** [comment]
I've created the wiki page [here](https://github.com/bcgov/nr-spar/wiki/Why-we-use-responsive-design)
