### ISSUE TITLE
Spike for #814 - change in PKG files

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#853]
**Describe the task**
Understand the changes needed to the PKG files for the legacy application to build the redirect need as well as turn off the A class indicator in the Seedlot registration screen.

**Acceptance Criteria**
- [ ] Documented in confluence
- [ ] Genetic Class indicator is locked to B class in the registration screens:

![Image](https://github.com/bcgov/nr-spar/assets/64149835/52cc7fd7-b03e-407f-8bfb-cebe25a44cc4)

Related to task #814 

Links:

https://testapps.nrs.gov.bc.ca/ext/spar/?

**Comment by craigyu** [comment]
The implementation of the genetic class dropdown is here:
`source/ear/src/main/java/ca/bc/gov/mof/spar/web/form/Spr01SeedlotRegForm.java`


## Limiting the dropdown options
The variable of the genetic class codes is instantiated on line 111:
```java
 private OptionBean[] geneticClassCodes;
```

It is then populated with values by calling a `codeManager` function on line 2898
```java
geneticClassCodes = codesManager.getCodes("GENETIC_CLASS");
```

The implementation of the `CodeManager` is here:
`source/ear/src/main/java/ca/bc/gov/mof/sil/webade/db/CodesManager.java`

It is unclear how exactly the application is requesting these genetic class codes but it might have something to do with the `GeneticClassCodeJDBCAdaptor` located at: `source/ear/src/main/java/ca/bc/gov/mof/spar/data/adaptors/GeneticClassCodeJDBCAdaptor.java`

Ultimately, considering a new genetic class code is very unlikely to be added in the future, it does not matter how the application is getting the codes from the database.

For our purpose, a simple solution is to hard code this `geneticClassCodes` variable like this (line 2900):
```java
        // geneticClassCodes = codesManager.getCodes("GENETIC_CLASS");
        CodeBean bClassBean = new CodeBean("GENETIC_CLASS", "B", "Natural Stand Seed or Cuttings");
        geneticClassCodes = (OptionBean[]) new CodeBean[]{bClassBean};
```
A review is needed to verify if the code is correct and usable, so far VSC isn't complaining so I assume it's fine.
![Image](https://github.com/bcgov/nr-spar/assets/25162561/7ae5c1c2-c8a0-4ba1-979b-aa6439f26df0)

## Make class B the default

On line 349 there is a function called `setDefaults()`, default values are set here, an example is how the default seedlot status code is set:
```java
 //set the status to INC for new records
dataBean.setP_seedlot_status_code("INC");
```

We can do something similar:
```java
//set the default genetic class code
dataBean.setP_genetic_class_code("B");
```
![Image](https://github.com/bcgov/nr-spar/assets/25162561/7ac5f173-4c4a-4751-97bb-56f32b124991)

At this point, users should not be able to select "A" as the genetic class.

## Locking the dropdown
the locking mechanism is implemented here
```java
    /**
     * Rules
     * Locked if existing record
     *
     */
    public boolean isGeneticClassEnabled()
    {
        if(StringUtils.getInstance().hasAValue(dataBean.getP_revision_count()))
        {
            return false;
        }
            return true;
    }
```

We could make it so that the `isGeneticClassEnabled` function is always returning false:
```java
    /**
     * Rules
     * Locked if existing record
     *
     */
    public boolean isGeneticClassEnabled()
    {
       return false;
    }
```

## Conclusion
If my understanding is correct, the code here will be compiled and new jsp files should be generated, once these new files are published, the desired features should be achieved.
