### ISSUE TITLE
My Seedlots Page Test Plan

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#920]
> Create a test plan for My Seedlots page. Try to cover all the functionalities.

### Implement a Cypress test on page `/seedlots/my-seedlots`

- [ ] Search functionality is working properly.
- [ ] Sort functionality is working as expected.
- [ ] Buttons are working as expected.
- [ ] Check the number of entries in the table is correct.

**Note**: Do we need to change the cursor for the table rows?

![Image](https://github.com/bcgov/nr-spar/assets/31422051/fa4c6947-9d94-42b7-bcaa-4593973b0d90)

**Comment by ngunner15** [comment]
**Test Case Steps**

1. User can see the table of My Seedlots.
2. User clicks on any seedlot row.
3. User can sort the table by clicking on any of the columns.
4. User can use the search bar.
5. Total number of seedlots are shown at the bottom of the table.
6. User can decide how many rows of seedlots are shown on one page.
7. User clicks on the next page.
8. User can click on 'Register a new seedlot' button.


**Test Case Expected Results**

After step 2:
It sends user to that seedlot's page.

After step 3:
User clicks on Seedlot number column and the table is rearranged in ascending order of Seedlot numbers.

After step 4:
Typing a particular seedlot number returns that seedlot's row.

After step 6:
User clicks the dropdown menu at the bottom of the table and chooses 10 instead of 20, only ten rows are shown on the current page.

After step7:
Next page of rows are shown.

After step 8:
It redirects to `seedlots/register-a-class` page.

**Comment by craigyu** [comment]
Good stuff! When testing I'd pay attention to step 2 when implementing it. After a user clicks on a row, it gets redirected to the seedlot details page, and on that page a bunch of calls are made, you might have to mock some of them, some are already mocked I believe, such as `/veg-codes`
